baseURL = "http://example.com/"
languageCode = "en-us"
title = "My Site"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params.social]
    GitHub = "H-Zeus"
    Email   = "daisy.win@foxmail.com"
    Wechat = "/images/me/wechat.png"


[params]
    since = 2018
    author = "Zeus"                           # Author's name
    avatar = "/images/me/wechat.jpeg"         # Author's avatar
    subtitle = "我会更好，因为我没有停止"        # Subtitle

    # cdn_url = ""       # Base CDN URL
    # home_mode = "post" # post or other
    # description = ""   # site description
    # keywords = ""      # site keywords

    # beian = ""
    # baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'